//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client8.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Wyjatek7", Namespace="http://schemas.datacontract.org/2004/07/KSR_WCF1")]
    [System.SerializableAttribute()]
    public partial class Wyjatek7 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int bField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string opisField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string a {
            get {
                return this.aField;
            }
            set {
                if ((object.ReferenceEquals(this.aField, value) != true)) {
                    this.aField = value;
                    this.RaisePropertyChanged("a");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int b {
            get {
                return this.bField;
            }
            set {
                if ((this.bField.Equals(value) != true)) {
                    this.bField = value;
                    this.RaisePropertyChanged("b");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string opis {
            get {
                return this.opisField;
            }
            set {
                if ((object.ReferenceEquals(this.opisField, value) != true)) {
                    this.opisField = value;
                    this.RaisePropertyChanged("opis");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IZadanie2")]
    public interface IZadanie2 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZadanie2/Test", ReplyAction="http://tempuri.org/IZadanie2/TestResponse")]
        string Test(string arg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZadanie2/Test", ReplyAction="http://tempuri.org/IZadanie2/TestResponse")]
        System.Threading.Tasks.Task<string> TestAsync(string arg);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IZadanie2Channel : Client8.ServiceReference1.IZadanie2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Zadanie2Client : System.ServiceModel.ClientBase<Client8.ServiceReference1.IZadanie2>, Client8.ServiceReference1.IZadanie2 {
        
        public Zadanie2Client() {
        }
        
        public Zadanie2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Zadanie2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Zadanie2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Zadanie2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Test(string arg) {
            return base.Channel.Test(arg);
        }
        
        public System.Threading.Tasks.Task<string> TestAsync(string arg) {
            return base.Channel.TestAsync(arg);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IZadanie7")]
    public interface IZadanie7 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZadanie7/RzucWyjatek7", ReplyAction="http://tempuri.org/IZadanie7/RzucWyjatek7Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(Client8.ServiceReference1.Wyjatek7), Action="http://tempuri.org/IZadanie7/RzucWyjatek7Wyjatek7Fault", Name="Wyjatek7", Namespace="http://schemas.datacontract.org/2004/07/KSR_WCF1")]
        void RzucWyjatek7(string a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZadanie7/RzucWyjatek7", ReplyAction="http://tempuri.org/IZadanie7/RzucWyjatek7Response")]
        System.Threading.Tasks.Task RzucWyjatek7Async(string a, int b);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IZadanie7Channel : Client8.ServiceReference1.IZadanie7, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Zadanie7Client : System.ServiceModel.ClientBase<Client8.ServiceReference1.IZadanie7>, Client8.ServiceReference1.IZadanie7 {
        
        public Zadanie7Client() {
        }
        
        public Zadanie7Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Zadanie7Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Zadanie7Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Zadanie7Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void RzucWyjatek7(string a, int b) {
            base.Channel.RzucWyjatek7(a, b);
        }
        
        public System.Threading.Tasks.Task RzucWyjatek7Async(string a, int b) {
            return base.Channel.RzucWyjatek7Async(a, b);
        }
    }
}
